# Generated by Django 4.1.1 on 2022-09-27 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateField(auto_now_add=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('initiatedBy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='frSender', to=settings.AUTH_USER_MODEL)),
                ('initiatedTowards', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='frReceiver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
