# Generated by Django 4.1.1 on 2022-09-27 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialmedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='initiatedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frSender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friends',
            name='initiatedTowards',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frReceiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
