# Generated by Django 4.1.1 on 2022-09-27 21:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialmedia', '0002_alter_friends_initiatedby_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friends',
            new_name='Friendship',
        ),
    ]
