# Generated by Django 4.1.1 on 2022-09-28 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_favorite'),
        ('socialmedia', '0004_friendshipnotification_bookfeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookfeed',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.review'),
        ),
        migrations.AlterField(
            model_name='bookfeed',
            name='notify',
            field=models.ManyToManyField(null=True, related_name='notificationFor', to=settings.AUTH_USER_MODEL),
        ),
    ]
