# Generated by Django 4.1.1 on 2022-09-29 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_favorite'),
        ('socialmedia', '0005_bookfeed_review_alter_bookfeed_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookfeed',
            name='favorite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.favorite'),
        ),
    ]
