# Generated by Django 4.1.1 on 2022-09-29 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_like'),
        ('socialmedia', '0006_bookfeed_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookfeed',
            name='like',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.like'),
        ),
    ]
