# Generated by Django 4.1.1 on 2022-10-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'required': 'Please provide book name'}, max_length=150, unique=True)),
                ('author', models.CharField(max_length=150)),
                ('publishDate', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('noOfPages', models.IntegerField()),
                ('image', models.ImageField(default='', upload_to='book-covers')),
                ('stock', models.IntegerField(default=10)),
            ],
        ),
    ]
