# Generated by Django 4.1.1 on 2022-10-10 14:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0002_alter_book_name'),
        ('shop', '0003_alter_stripepayment_amount'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('book', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('book', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('book', 'user')},
        ),
    ]
