# Generated by Django 4.1.1 on 2022-09-06 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempuser',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 6, 8, 1, 20, 90401, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='image',
            field=models.ImageField(default='images/DEFAULT_PROFILE_IMAGE_BACKEND_UPLOADED.png', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='user_code',
            field=models.IntegerField(blank=True, default=694197, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 6, 8, 1, 20, 88834, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_code',
            field=models.IntegerField(blank=True, default=508268, null=True, unique=True),
        ),
    ]
