# Generated by Django 4.1.1 on 2022-09-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempuser',
            name='user_code',
            field=models.IntegerField(blank=True, default=116376, unique=True),
        ),
    ]
