# Generated by Django 4.1.1 on 2022-09-06 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_tempuser_creation_alter_tempuser_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempuser',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 6, 8, 1, 47, 900035, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='user_code',
            field=models.IntegerField(blank=True, default=717285, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 6, 8, 1, 47, 898460, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_code',
            field=models.IntegerField(blank=True, default=389904, null=True, unique=True),
        ),
    ]
