# Generated by Django 4.1.1 on 2022-09-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_passwordrecovery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordrecovery',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
