# Generated by Django 4.1.1 on 2022-09-06 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_tempuser_creation_alter_tempuser_user_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempuser',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 6, 9, 34, 5, 678216, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='user_code',
            field=models.IntegerField(blank=True, default=388667, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 6, 9, 34, 5, 676630, tzinfo=datetime.timezone.utc)),
        ),
    ]
