# Generated by Django 4.1.1 on 2022-10-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tempUser',
            field=models.BooleanField(default=False),
        ),
    ]
