# Generated by Django 4.1.1 on 2022-09-06 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_age_user_country_alter_tempuser_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempuser',
            name='age',
            field=models.IntegerField(default=18, validators=[django.core.validators.MinValueValidator(15)]),
        ),
        migrations.AddField(
            model_name='tempuser',
            name='country',
            field=models.CharField(default='Pakistan', max_length=50),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='user_code',
            field=models.IntegerField(blank=True, default=730078, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
