# Generated by Django 4.1.1 on 2022-09-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_tempuser_age_tempuser_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempuser',
            name='user_code',
            field=models.IntegerField(blank=True, default=151072, null=True, unique=True),
        ),
    ]
